application: digital-copy-market
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /fonts
  static_dir: fonts
- url: /js
  static_dir: js
- url: /css 
  static_dir: css
- url: /images
  static_dir: images
- url: /myprofile
  script: digi.application
  login: required
- url: /entercode
  script: digi.application
  login: required
- url: /.*
  script: digi.application
  secure: always

libraries:
- name: jinja2
  version: latest
  
inbound_services:
- mail
